<Project Sdk="Microsoft.NET.Sdk">

  <!--<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>-->

  <PropertyGroup>
    <Version>0.0.1</Version>
    <PackageId>Stef.Microsoft.SemanticKernel.Retry</PackageId>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ApplicationIcon>../../resources/icon.ico</ApplicationIcon>
    <Copyright>Copyright © Stef Heyenrath</Copyright>
    <Authors>Stef Heyenrath</Authors>
    <PackageIcon>icon.png</PackageIcon>
    <Product>Microsoft SemanticKernel Resilience Extensions</Product>
    <Description>'WithRetryAsync' extension for Microsoft SemanticKernel to handle 'Rate limit reached' exceptions using retries.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/StefH/Microsoft.SemanticKernel.WithRetry</PackageProjectUrl>
    <RepositoryUrl>https://github.com/StefH/Microsoft.SemanticKernel.WithRetry</RepositoryUrl>
    <PackageTags>OpenAI, SemanticKernel, AI, ML, API, Chat, ChatGPT, Embeddings, Resilience, Retry, RetryAsync, Rate limit, TooManyRequests</PackageTags>
    <Title>Microsoft SemanticKernel Resilience Extensions</Title>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReadmeFile>PackageReadme.md</PackageReadmeFile>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../PackageReleaseNotes.txt"))</PackageReleaseNotes>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../resources/icon.png" Pack="true" PackagePath="" />
    <None Include="PackageReadme.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.68.0" />
  </ItemGroup>


</Project>
